#!/bin/bash
# EXECUTION GUIDE: Sales vs Rentals Categorization Fix
# 
# This script walks you through deploying and verifying the fix

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 SALES vs RENTALS CATEGORIZATION FIX"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📋 FILES MODIFIED:"
echo "  ✓ lib/models/Order.ts - Added 'orderType' field"
echo "  ✓ app/api/orders/route.ts - Set orderType on order creation"
echo "  ✓ app/api/admin/analytics/route.ts - Fixed sales/rental categorization"
echo ""

echo "📝 NEW FILES CREATED:"
echo "  ✓ migrate-order-types.js - Migration script for existing orders"
echo "  ✓ SALES_VS_RENTALS_FIX.md - Technical documentation"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 DEPLOYMENT STEPS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "STEP 1: Deploy code changes"
echo "  Command: git commit && git push (or deploy to production)"
echo "  Status: ✅ Ready - all changes are backward compatible"
echo ""

echo "STEP 2: Run migration to update existing orders"
echo "  Command: npx ts-node migrate-order-types.js"
echo "  Purpose: Analyzes all orders and assigns correct orderType"
echo "  Time: ~1-5 seconds depending on order count"
echo "  Safety: Creates no new records, only updates existing orders"
echo ""

echo "STEP 3: Verify in admin dashboard"
echo "  1. Log in as Super Admin or Finance Admin"
echo "  2. Go to Dashboard > Analytics"
echo "  3. Check Sales Revenue and Rental Revenue metrics"
echo "  4. Sales orders should appear under 'Sales Revenue'"
echo "  5. Rental orders should appear under 'Rental Revenue'"
echo "  6. Mixed orders count toward BOTH metrics"
echo ""

echo "STEP 4: Test with new orders"
echo "  Test 1: Create a SALES order (buy only)"
echo "    → Should appear in 'Sales Revenue' metric"
echo "  Test 2: Create a RENTAL order (rent only)"
echo "    → Should appear in 'Rental Revenue' metric"
echo "    → Caution fee should be tracked separately"
echo "  Test 3: Create MIXED order (buy + rent)"
echo "    → Sales revenue counts toward Sales"
echo "    → Rental revenue counts toward Rental"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 WHAT'S FIXED:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ BEFORE:"
echo "  • All orders recorded as 'Rentals' regardless of type"
echo "  • Dashboard showed incorrect metric distribution"
echo "  • Couldn't distinguish sales from rental revenue"
echo ""
echo "✅ AFTER:"
echo "  • Orders correctly categorized by type"
echo "  • Dashboard shows accurate Sales vs Rental split"
echo "  • Mixed orders counted correctly in both categories"
echo "  • Revenue calculated at item level, not order level"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔑 KEY TECHNICAL DETAILS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Order Type Determination:"
echo "  • orderType = 'rental'  ← Only rental items"
echo "  • orderType = 'sales'   ← Only sales items"
echo "  • orderType = 'mixed'   ← Both rental AND sales items"
echo ""
echo "Revenue Calculation:"
echo "  • Per-item basis (NOT per-order)"
echo "  • Each item → revenue goes to correct category (Sales or Rental)"
echo "  • Mixed orders contribute to BOTH totals"
echo ""
echo "Database Changes:"
echo "  • Added 'orderType' field to Order schema"
echo "  • Added index on orderType for fast filtering"
echo "  • Backward compatible - old orders still work"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ ALL SYSTEMS READY - DEPLOY WHEN READY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
